remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - requestsignature.php

style: dark
listen_for_clients_preferred_style: true

footer: 'My <a href="https://github.com/ThijmenNLD">GitHub</a>'

google_analytics: UA-NNNNNNNN-N
